In [ ]:
"""
In this notebook, the (almost) raw FAERS dataset is first processed. Then, the Disproportionality Analysis is performed.
Before beginning, download the provided files (link in README.md) and unpack them in PMD/data/raw/step_00
"""

In [1]:
import sys
sys.path.insert(0, '..')

import warnings
from joblib import Parallel, delayed

from sklearn.model_selection import GroupKFold

from src.data.io import read_df
from src.data.butina import butina_cluster
from src.data.descriptors import dataframe_2_ecfp
from src.dataset.dpa import *
from src.dataset.preprocessing import *

n_jobs = 64

/Users/miwan/miniforge3/envs/carbide/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Step 1

In [ ]:
"""
In step 1 the following operations are performed:
    - redundant columns removed,
    - strings for drugs, indications, dates, weights, and ages are evaluated,
    - drugs are combined with their indications (if present),
    - correct datatypes are assigned
"""

In [3]:
os.makedirs('../data/intermediate/step_01', exist_ok=True)

def process_step_1(file):
    out_path = f'../data/intermediate/step_01/chunk_{file.split("/")[-1].split("_")[-1].split(".")[0]}.joblib'

    df = pd.read_parquet(file)
    df = step_1(df=df)

    joblib.dump(df, out_path)
    return file

files = sorted(glob.glob(f'../data/raw/*.parquet'))

results = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
    delayed(process_step_1)(file) for file in files
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   7 out of  64 | elapsed:  1.1min remaining:  8.7min
[Parallel(n_jobs=64)]: Done  14 out of  64 | elapsed:  1.1min remaining:  3.8min
[Parallel(n_jobs=64)]: Done  21 out of  64 | elapsed:  1.1min remaining:  2.2min
[Parallel(n_jobs=64)]: Done  28 out of  64 | elapsed:  1.1min remaining:  1.4min
[Parallel(n_jobs=64)]: Done  35 out of  64 | elapsed:  1.1min remaining:   53.9s
[Parallel(n_jobs=64)]: Done  42 out of  64 | elapsed:  1.1min remaining:   34.1s
[Parallel(n_jobs=64)]: Done  49 out of  64 | elapsed:  1.1min remaining:   20.0s
[Parallel(n_jobs=64)]: Done  56 out of  64 | elapsed:  1.1min remaining:    9.3s
[Parallel(n_jobs=64)]: Done  64 out of  64 | elapsed:  1.1min finished

In [4]:
joblib.load('../data/intermediate/step_01/chunk_1.joblib')

,primaryid,event_dt,fda_dt,sex,age_months,age_group,weight_kg,reactions,drug_indi
0,153086732,2018-08-14,2018-08-22,M,960.0,Elderly,71.188004,"[blood pressure decreased, heart rate irregular]","[(1, PS, revlimid, plasma cell myeloma), (2, S..."
1,153088091,<NA>,2018-08-22,M,<NA>,<NA>,<NA>,[tooth loss],"[(1, PS, humira, psoriasis), (2, SS, humira, p..."
2,153088391,<NA>,2018-08-22,F,420.0,Adult,<NA>,[drug effect incomplete],"[(1, PS, otezla, psoriasis)]"
3,153090461,<NA>,2018-08-23,F,780.0,Elderly,<NA>,[injection site discolouration],"[(1, PS, enbrel, rheumatoid arthritis)]"
4,153090671,2018-08-15,2018-08-23,<NA>,<NA>,<NA>,<NA>,"[myocardial strain, pleural effusion]","[(1, PS, eligard, prostate cancer)]"
...,...,...,...,...,...,...,...,...,...
276365,152884242,<NA>,2018-08-17,F,648.0,Adult,<NA>,"[influenza, multiple sclerosis relapse, stress]","[(1, PS, tysabri, multiple sclerosis)]"
276366,152884321,<NA>,2018-08-17,F,<NA>,<NA>,<NA>,[alopecia],"[(1, PS, tecfidera, multiple sclerosis), (2, C..."
276367,152886135,<NA>,2018-08-17,M,<NA>,<NA>,90.0,"[arthralgia, circumstance or information capab...","[(1, PS, benlysta, systemic lupus erythematosu..."
276368,152886161,<NA>,2018-08-17,M,468.0,Adult,<NA>,"[haematoma, neoplasm skin, pain in extremity]","[(1, PS, lamotrigine., product used for unknow..."
276369,152886721,2016-01-24,2018-08-17,F,720.0,Adult,136.75,"[dehydration, sepsis]","[(1, PS, trastuzumab emtansine, her-2 positive..."

### Step 2

In [ ]:
"""
In step 2 the following operations are performed:
    - mapping of reactions from LLT to PTs,
    - counting of drug types,
    - filtering of the dataframe based on set max_ps, max_drug, and max_reactions
"""

In [5]:
os.makedirs(f'../data/intermediate/step_02_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_02_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_02_secondary', exist_ok=True)

"""
The llt_2_pt.tsv file contains mapping from LLT descriptions used in the FAERS database to MedDRA Preferred Terms (PT), which we are not allowed to make public due to license restrictions. To make running the notebook possible, we make available llt_2_pt_encoded.tsv file, which encodes the PT as just indices. See README.md in PMD/data/mappings for a link to a website where the license can be obtained.
"""
use_encoded = True

if use_encoded:
    llt_2_pt = read_df('../data/mappings/llt_2_pt_encoded.tsv')
    terms_col = 'PT_enc'
else:
    llt_2_pt = read_df('../data/mappings/llt_2_pt.tsv')
    terms_col = 'PT'

pts = tuple(sorted(set(llt_2_pt[terms_col].tolist())))

llt_2_pt = {llt: pt for llt, pt in zip(llt_2_pt['LLT'].tolist(), llt_2_pt[terms_col].tolist())}

pt_2_idx = {pt: idx for idx, pt in enumerate(pts)}
idx_2_pt = {idx: pt for idx, pt in enumerate(pts)}

joblib.dump(pt_2_idx, '../data/mappings/pt_2_idx.joblib')
joblib.dump(idx_2_pt, '../data/mappings/idx_2_pt.joblib')

['../data/mappings/idx_2_pt.joblib']

In [6]:
def process_step_2(file, output_dir, llt_2_pt, max_ps, max_drug, max_reactions, filter_type):
    """
    Parallel wrapper for step 2
    """
    out_path = f'{output_dir}/{file.split("/")[-1]}'

    df = joblib.load(file)
    df = step_2(
        df=df,
        llt_2_pt=llt_2_pt,
        max_ps=max_ps,
        max_drug=max_drug,
        max_reactions=max_reactions,
        filter_type=filter_type
    )

    joblib.dump(df, out_path)
    return file

files = sorted(glob.glob(f'../data/intermediate/step_01/chunk*.joblib'))
tasks = []

for file in files:
    tasks.append((file, '../data/intermediate/step_02_mono', None, 10, 20, 'mono'))

for file in files:
    tasks.append((file, '../data/intermediate/step_02_primary', 1, None, 20, 'primary'))

for file in files:
    tasks.append((file, '../data/intermediate/step_02_secondary', None, 10, 20, 'secondary'))

results = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
    delayed(process_step_2)(file=file, output_dir=output_dir, llt_2_pt=llt_2_pt, max_ps=max_ps, max_drug=max_drug, max_reactions=max_reactions, filter_type=filter_type)
    for file, output_dir, max_ps, max_drug, max_reactions, filter_type in tasks
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done  17 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done  53 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done  85 out of 192 | elapsed:  2.1min remaining:  2.7min
[Parallel(n_jobs=64)]: Done 105 out of 192 | elapsed:  2.2min remaining:  1.8min
[Parallel(n_jobs=64)]: Done 125 out of 192 | elapsed:  2.3min remaining:  1.2min
[Parallel(n_jobs=64)]: Done 145 out of 192 | elapsed:  3.3min remaining:  1.1min
[Parallel(n_jobs=64)]: Done 165 out of 192 | elapsed:  3.4min remaining:   33.9s
[Parallel(n_jobs=64)]: Done 185 out of 192 | elapsed:  3.6min remaining:    8.1s
[Parallel(n_jobs=64)]: Done 192 out of 192 | elapsed:  3.6min finished

In [7]:
joblib.load('../data/intermediate/step_02_mono/chunk_1.joblib')

,primaryid,event_dt,fda_dt,sex,age_months,age_group,weight_kg,reactions,role_code,drug_name,indication
0,153086732,2018-08-14,2018-08-22,M,960.0,Elderly,71.188004,"[PT_02918, PT_08975]",<NA>,<NA>,<NA>
1,153088091,<NA>,2018-08-22,M,<NA>,<NA>,<NA>,[PT_19770],<NA>,<NA>,<NA>
2,153088391,<NA>,2018-08-22,F,420.0,Adult,<NA>,[PT_19443],PS,otezla,psoriasis
3,153090461,<NA>,2018-08-23,F,780.0,Elderly,<NA>,[PT_10515],PS,enbrel,rheumatoid arthritis
4,153090671,2018-08-15,2018-08-23,<NA>,<NA>,<NA>,<NA>,"[PT_13209, PT_15697]",PS,eligard,prostate cancer
...,...,...,...,...,...,...,...,...,...,...,...
270594,152884242,<NA>,2018-08-17,F,648.0,Adult,<NA>,"[PT_10387, PT_13031, PT_18947]",PS,tysabri,multiple sclerosis
270595,152884321,<NA>,2018-08-17,F,<NA>,<NA>,<NA>,[PT_00760],<NA>,<NA>,<NA>
270596,152886135,<NA>,2018-08-17,M,<NA>,<NA>,90.0,"[PT_01713, PT_04530, PT_05314, PT_05798, PT_06...",<NA>,<NA>,<NA>
270597,152886161,<NA>,2018-08-17,M,468.0,Adult,<NA>,"[PT_08774, PT_13532, PT_14594]",PS,lamotrigine.,product used for unknown indication
270598,152886721,2016-01-24,2018-08-17,F,720.0,Adult,136.75,"[PT_05737, PT_18079]",<NA>,<NA>,<NA>

### Step 3

In [ ]:
"""
In step 3 the following operations are performed:
    - mapping of demographic values to numpy arrays
    - mapping of FAERS drug descriptions to active ingredients
    - removal of rows with missing reactions or actives
"""

In [10]:
os.makedirs(f'../data/intermediate/step_03_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_03_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_03_secondary', exist_ok=True)

os.makedirs(f'../data/mappings/wq_mono', exist_ok=True)
os.makedirs(f'../data/mappings/wq_primary', exist_ok=True)
os.makedirs(f'../data/mappings/wq_secondary', exist_ok=True)

token_map = read_df('../data/mappings/token_mapping.tsv')  # mapping from drug descriptions to active ingredients

def process_step_3(file, output_dir, tok_map, wbk, wsu, waesk, waesu):
    out_path = f'{output_dir}/{file.split("/")[-1]}'

    df = joblib.load(file)
    df = step_3(
        df=df,
        token_map=tok_map,
        wq_both_known=wbk,
        wq_sex_unknown=wsu,
        wq_age_estim_sex_known=waesk,
        wq_age_estim_sex_unknown=waesu
    )

    joblib.dump(df, out_path)
    return file

In [11]:
both_known, sex_unknown, age_estim_sex_known, age_estim_sex_unknown = prepare_weight_mapping(f'../data/intermediate/step_02_mono')

joblib.dump(both_known, f'../data/mappings/wq_mono/wq_both_known.joblib')
joblib.dump(sex_unknown, f'../data/mappings/wq_mono/wq_sex_unknown.joblib')
joblib.dump(age_estim_sex_known, f'../data/mappings/wq_mono/wq_age_estim_sex_known.joblib')
joblib.dump(age_estim_sex_unknown, f'../data/mappings/wq_mono/wq_age_estim_sex_unknown.joblib')

tasks = []

for file in sorted(glob.glob(f'../data/intermediate/step_02_mono/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_03_mono'))

results = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
    delayed(process_step_3)(file, output_dir, token_map, both_known, sex_unknown, age_estim_sex_known, age_estim_sex_unknown)
    for file, output_dir in tasks
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   7 out of  64 | elapsed:   17.3s remaining:  2.3min
[Parallel(n_jobs=64)]: Done  14 out of  64 | elapsed:   18.1s remaining:  1.1min
[Parallel(n_jobs=64)]: Done  21 out of  64 | elapsed:   18.6s remaining:   38.1s
[Parallel(n_jobs=64)]: Done  28 out of  64 | elapsed:   19.3s remaining:   24.8s
[Parallel(n_jobs=64)]: Done  35 out of  64 | elapsed:   20.0s remaining:   16.6s
[Parallel(n_jobs=64)]: Done  42 out of  64 | elapsed:   20.7s remaining:   10.8s
[Parallel(n_jobs=64)]: Done  49 out of  64 | elapsed:   21.4s remaining:    6.5s
[Parallel(n_jobs=64)]: Done  56 out of  64 | elapsed:   21.9s remaining:    3.1s
[Parallel(n_jobs=64)]: Done  64 out of  64 | elapsed:   22.1s finished

In [12]:
both_known, sex_unknown, age_estim_sex_known, age_estim_sex_unknown = prepare_weight_mapping(f'../data/intermediate/step_02_primary')

joblib.dump(both_known, f'../data/mappings/wq_primary/wq_both_known.joblib')
joblib.dump(sex_unknown, f'../data/mappings/wq_primary/wq_sex_unknown.joblib')
joblib.dump(age_estim_sex_known, f'../data/mappings/wq_primary/wq_age_estim_sex_known.joblib')
joblib.dump(age_estim_sex_unknown, f'../data/mappings/wq_primary/wq_age_estim_sex_unknown.joblib')

tasks = []

for file in sorted(glob.glob(f'../data/intermediate/step_02_primary/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_03_primary'))

results = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
    delayed(process_step_3)(file, output_dir, token_map, both_known, sex_unknown, age_estim_sex_known, age_estim_sex_unknown)
    for file, output_dir in tasks
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   7 out of  64 | elapsed:   19.5s remaining:  2.6min
[Parallel(n_jobs=64)]: Done  14 out of  64 | elapsed:   24.1s remaining:  1.4min
[Parallel(n_jobs=64)]: Done  21 out of  64 | elapsed:   26.4s remaining:   54.0s
[Parallel(n_jobs=64)]: Done  28 out of  64 | elapsed:   27.5s remaining:   35.4s
[Parallel(n_jobs=64)]: Done  35 out of  64 | elapsed:   28.2s remaining:   23.3s
[Parallel(n_jobs=64)]: Done  42 out of  64 | elapsed:   28.8s remaining:   15.1s
[Parallel(n_jobs=64)]: Done  49 out of  64 | elapsed:   29.2s remaining:    8.9s
[Parallel(n_jobs=64)]: Done  56 out of  64 | elapsed:   29.3s remaining:    4.2s
[Parallel(n_jobs=64)]: Done  64 out of  64 | elapsed:   29.4s finished

In [13]:
both_known, sex_unknown, age_estim_sex_known, age_estim_sex_unknown = prepare_weight_mapping(f'../data/intermediate/step_02_secondary')

joblib.dump(both_known, f'../data/mappings/wq_secondary/wq_both_known.joblib')
joblib.dump(sex_unknown, f'../data/mappings/wq_secondary/wq_sex_unknown.joblib')
joblib.dump(age_estim_sex_known, f'../data/mappings/wq_secondary/wq_age_estim_sex_known.joblib')
joblib.dump(age_estim_sex_unknown, f'../data/mappings/wq_secondary/wq_age_estim_sex_unknown.joblib')

tasks = []

for file in sorted(glob.glob(f'../data/intermediate/step_02_secondary/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_03_secondary'))

results = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
    delayed(process_step_3)(file, output_dir, token_map, both_known, sex_unknown, age_estim_sex_known, age_estim_sex_unknown)
    for file, output_dir in tasks
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   7 out of  64 | elapsed:   34.4s remaining:  4.7min
[Parallel(n_jobs=64)]: Done  14 out of  64 | elapsed:   39.8s remaining:  2.4min
[Parallel(n_jobs=64)]: Done  21 out of  64 | elapsed:   41.9s remaining:  1.4min
[Parallel(n_jobs=64)]: Done  28 out of  64 | elapsed:   42.8s remaining:   55.1s
[Parallel(n_jobs=64)]: Done  35 out of  64 | elapsed:   43.5s remaining:   36.1s
[Parallel(n_jobs=64)]: Done  42 out of  64 | elapsed:   44.0s remaining:   23.1s
[Parallel(n_jobs=64)]: Done  49 out of  64 | elapsed:   44.5s remaining:   13.6s
[Parallel(n_jobs=64)]: Done  56 out of  64 | elapsed:   44.6s remaining:    6.4s
[Parallel(n_jobs=64)]: Done  64 out of  64 | elapsed:   44.7s finished

In [14]:
joblib.load('../data/intermediate/step_03_mono/chunk_1.joblib')

,primaryid,sex,age_group,reactions,role_code,drug_name,indication,weight,active
2,153088391,F,Adult,[PT_19443],PS,otezla,psoriasis,Unknown,apremilast
3,153090461,F,Elderly,[PT_10515],PS,enbrel,rheumatoid arthritis,Unknown,etanercept
4,153090671,Unknown,Unknown,"[PT_13209, PT_15697]",PS,eligard,prostate cancer,Unknown,leuprolide
7,153091271,F,Unknown,[PT_06089],PS,otezla,psoriasis,Unknown,apremilast
8,153091362,M,Adult,"[PT_10199, PT_14121, PT_15866, PT_16294, PT_16...",PS,remicade,crohn's disease,High,infliximab
...,...,...,...,...,...,...,...,...,...
270589,152877271,M,Unknown,"[PT_02973, PT_06248, PT_07586, PT_08617, PT_09...",PS,humira,rheumatoid arthritis,Unknown,adalimumab
270591,152880041,M,Unknown,"[PT_06381, PT_10671]",PS,xanax,<NA>,Unknown,alprazolam
270592,152881111,M,Adult,[PT_00997],PS,amoxicilline,tooth extraction,Unknown,amoxicillin
270594,152884242,F,Adult,"[PT_10387, PT_13031, PT_18947]",PS,tysabri,multiple sclerosis,Unknown,natalizumab
270597,152886161,M,Adult,"[PT_08774, PT_13532, PT_14594]",PS,lamotrigine.,product used for unknown indication,Unknown,lamotrigine

### Step 4

In [ ]:
"""
In step 4 the following operations are performed:
    - mapping of active ingredients to SMILES strings
    - check for completeness of mapping
"""

In [15]:
os.makedirs(f'../data/intermediate/step_04_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_04_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_04_secondary', exist_ok=True)

smiles_mapping = read_df('../data/mappings/smiles_mapping.tsv')  # mapping from active ingredient names to SMILES strings

smiles = tuple(sorted(set(smiles_mapping['SMILES'])))
smi_2_idx = {smi:idx for idx, smi in enumerate(smiles)}
idx_2_smi = {idx:smi for idx, smi in enumerate(smiles)}

joblib.dump(smi_2_idx, '../data/mappings/smi_2_idx.joblib')
joblib.dump(idx_2_smi, '../data/mappings/idx_2_smi.joblib')

['../data/mappings/idx_2_smi.joblib']

In [19]:
def process_step_4(file, output_dir):
    out_path = f'{output_dir}/{file.split("/")[-1]}'

    df = joblib.load(file)
    df = step_4(
        df=df,
        smiles_mapping=smiles_mapping,
        smiles_col='SMILES'
    )

    joblib.dump(df, out_path)
    return file

tasks = []

for file in sorted(glob.glob(f'../data/intermediate/step_03_mono/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_04_mono'))

for file in sorted(glob.glob(f'../data/intermediate/step_03_primary/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_04_primary'))

for file in sorted(glob.glob(f'../data/intermediate/step_03_secondary/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_04_secondary'))


results = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
    delayed(process_step_4)(file, output_dir)
    for file, output_dir in tasks
)

[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
[Parallel(n_jobs=32)]: Done   8 tasks      | elapsed:    2.8s
[Parallel(n_jobs=32)]: Done  21 tasks      | elapsed:    3.2s
[Parallel(n_jobs=32)]: Done  34 tasks      | elapsed:    3.6s
[Parallel(n_jobs=32)]: Done  49 tasks      | elapsed:    4.4s
[Parallel(n_jobs=32)]: Done  64 tasks      | elapsed:    4.5s
[Parallel(n_jobs=32)]: Done  81 tasks      | elapsed:    6.4s
[Parallel(n_jobs=32)]: Done  98 tasks      | elapsed:    7.8s
[Parallel(n_jobs=32)]: Done 117 tasks      | elapsed:    8.8s
[Parallel(n_jobs=32)]: Done 149 out of 192 | elapsed:   13.1s remaining:    3.8s
[Parallel(n_jobs=32)]: Done 169 out of 192 | elapsed:   14.6s remaining:    2.0s
[Parallel(n_jobs=32)]: Done 189 out of 192 | elapsed:   16.6s remaining:    0.3s
[Parallel(n_jobs=32)]: Done 192 out of 192 | elapsed:   16.7s finished

In [21]:
joblib.load('../data/intermediate/step_04_mono/chunk_1.joblib')

,primaryid,Sex,Age,reactions,role_code,Weight,active,SMILES
0,153088391,F,Adult,[PT_19443],PS,Unknown,apremilast,[CCOc1cc(C(CS(C)(=O)=O)N2C(=O)c3cccc(NC(C)=O)c...
1,153091271,F,Unknown,[PT_06089],PS,Unknown,apremilast,[CCOc1cc(C(CS(C)(=O)=O)N2C(=O)c3cccc(NC(C)=O)c...
2,153094721,M,Elderly,"[PT_15251, PT_19160]",PS,Unknown,pirfenidone,[Cc1ccc(=O)n(-c2ccccc2)c1]
3,153095371,F,Elderly,[PT_04350],PS,High,amiodarone,[CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I...
4,153099631,Unknown,Unknown,"[PT_03253, PT_12119]",PS,Unknown,ribociclib,[CN(C)C(=O)c1cc2cnc(Nc3ccc(N4CCNCC4)cn3)nc2n1C...
...,...,...,...,...,...,...,...,...
72313,152868501,M,Adolescent,[PT_08733],PS,Unknown,paliperidone,[Cc1nc2n(c(=O)c1CCN1CCC(c3noc4cc(F)ccc34)CC1)C...
72314,152869822,F,Elderly,"[PT_09726, PT_18013]",PS,Unknown,levofloxacin,[CC1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1...
72315,152880041,M,Unknown,"[PT_06381, PT_10671]",PS,Unknown,alprazolam,[Cc1nnc2n1-c1ccc(Cl)cc1C(c1ccccc1)=NC2]
72316,152881111,M,Adult,[PT_00997],PS,Unknown,amoxicillin,[CC1(C)SC2C(NC(=O)C(N)c3ccc(O)cc3)C(=O)N2C1C(=...
72317,152886161,M,Adult,"[PT_08774, PT_13532, PT_14594]",PS,Unknown,lamotrigine,[Nc1nnc(-c2cccc(Cl)c2Cl)c(N)n1]

### Step 5

In [ ]:
"""
In step 5 the following operations are performed:
- encoding of reactions and SMILES strings to facilitate the subsequent DPA analysis
"""

In [22]:
os.makedirs(f'../data/intermediate/step_05_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_05_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_05_secondary', exist_ok=True)

smi_2_idx = joblib.load('../data/mappings/smi_2_idx.joblib')
pt_2_idx = joblib.load('../data/mappings/pt_2_idx.joblib')

In [23]:
def process_step_5(file, output_dir):
    out_path = f'{output_dir}/{file.split("/")[-1]}'

    df = joblib.load(file)
    df = step_5(
        df=df,
        smi_2_idx=smi_2_idx,  # mapping of SMILES to its index
        pt_2_idx=pt_2_idx     # MedDRA PT to idx mapping
    )

    joblib.dump(df, out_path)
    return file

tasks = []

for file in sorted(glob.glob(f'../data/intermediate/step_04_mono/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_05_mono'))

for file in sorted(glob.glob(f'../data/intermediate/step_04_primary/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_05_primary'))

for file in sorted(glob.glob(f'../data/intermediate/step_04_secondary/chunk*.joblib')):
    tasks.append((file, '../data/intermediate/step_05_secondary'))

results = Parallel(n_jobs=n_jobs, verbose=1)(
    delayed(process_step_5)(file, output_dir)
    for file, output_dir in tasks
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done 192 out of 192 | elapsed:   23.0s finished

In [24]:
joblib.load('../data/intermediate/step_05_mono/chunk_1.joblib')

           Sex         Age   Weight              reac_enc smi_enc
0            F       Adult  Unknown               [19442]  [1222]
1            F     Unknown  Unknown                [6088]  [1222]
2            M     Elderly  Unknown        [15250, 19159]  [2038]
3            F     Elderly     High                [4349]  [1030]
4      Unknown     Unknown  Unknown         [3252, 12118]  [1314]
...        ...         ...      ...                   ...     ...
72313        M  Adolescent  Unknown                [8732]  [2130]
72314        F     Elderly  Unknown         [9725, 18012]   [741]
72315        M     Unknown  Unknown         [6380, 10670]  [2157]
72316        M       Adult  Unknown                 [996]   [593]
72317        M       Adult  Unknown  [8773, 13531, 14593]  [2538]

[72318 rows x 5 columns]

### Step 6

In [ ]:
"""
In step 6 the following operations are performed:
    - data stratification by various combinations of demographic factors
    - counting of individual entries (i.e. instead of having 100 rows with the same data, there will be a single row with its count)

This step requires around 32GB of RAM.
"""

In [25]:
os.makedirs(f'../data/intermediate/step_06_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_06_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_06_secondary', exist_ok=True)

def process_step_6_1(file):
    df = joblib.load(file)
    return step_6_1(df=df)

def process_dataset(input_pattern, output_dir):
    files = sorted(glob.glob(input_pattern))

    dfs = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
        delayed(process_step_6_1)(file) for file in files
    )

    processed_df = step_6_2(pd.concat(dfs, ignore_index=True))

    for strat in processed_df.strat.unique():
        sub_df = processed_df[processed_df.strat == strat].reset_index(drop=True)
        joblib.dump(sub_df, f'{output_dir}/strat_{strat}.joblib')

    return output_dir

_ = process_dataset(f'../data/intermediate/step_05_mono/chunk*.joblib', '../data/intermediate/step_06_mono')
_ = process_dataset(f'../data/intermediate/step_05_primary/chunk*.joblib', '../data/intermediate/step_06_primary')
_ = process_dataset(f'../data/intermediate/step_05_secondary/chunk*.joblib', '../data/intermediate/step_06_secondary')

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   7 out of  64 | elapsed:    2.7s remaining:   21.7s
[Parallel(n_jobs=64)]: Done  14 out of  64 | elapsed:    3.1s remaining:   11.0s
[Parallel(n_jobs=64)]: Done  21 out of  64 | elapsed:    3.5s remaining:    7.2s
[Parallel(n_jobs=64)]: Done  28 out of  64 | elapsed:    3.9s remaining:    5.0s
[Parallel(n_jobs=64)]: Done  35 out of  64 | elapsed:    4.3s remaining:    3.6s
[Parallel(n_jobs=64)]: Done  42 out of  64 | elapsed:    4.7s remaining:    2.5s
[Parallel(n_jobs=64)]: Done  49 out of  64 | elapsed:    5.1s remaining:    1.6s
[Parallel(n_jobs=64)]: Done  56 out of  64 | elapsed:    5.5s remaining:    0.8s
[Parallel(n_jobs=64)]: Done  64 out of  64 | elapsed:    6.0s finished
[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   7 out of  64 | elapsed:    5.2s remaining:   42.0s
[Parallel(n_jobs=64)]: Done  14 out of  64 | elapsed:    6.6s remaining:   23.5s
[Parallel(n_jobs=64)]: Done  21 out of  64 | elapsed:    7.7s remaining:   15.8s
[Parallel(n_jobs=64)]: Done  28 out of  64 | elapsed:    9.0s remaining:   11.5s
[Parallel(n_jobs=64)]: Done  35 out of  64 | elapsed:   11.0s remaining:    9.1s
[Parallel(n_jobs=64)]: Done  42 out of  64 | elapsed:   12.3s remaining:    6.4s
[Parallel(n_jobs=64)]: Done  49 out of  64 | elapsed:   13.4s remaining:    4.1s
[Parallel(n_jobs=64)]: Done  56 out of  64 | elapsed:   14.5s remaining:    2.1s
[Parallel(n_jobs=64)]: Done  64 out of  64 | elapsed:   15.8s finished
[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   7 out of  64 | elapsed:    9.4s remaining:  1.3min
[Parallel(n_jobs=64)]: Done  14 out of  64 | elapsed:   14.1s remaining:   50.2s
[Parallel(n_jobs=64)]: Done  21 out of  64 | elapsed:   16.0s remaining:   32.8s
[Parallel(n_jobs=64)]: Done  28 out of  64 | elapsed:   18.0s remaining:   23.2s
[Parallel(n_jobs=64)]: Done  35 out of  64 | elapsed:   19.9s remaining:   16.5s
[Parallel(n_jobs=64)]: Done  42 out of  64 | elapsed:   21.7s remaining:   11.4s
[Parallel(n_jobs=64)]: Done  49 out of  64 | elapsed:   23.4s remaining:    7.2s
[Parallel(n_jobs=64)]: Done  56 out of  64 | elapsed:   25.1s remaining:    3.6s
[Parallel(n_jobs=64)]: Done  64 out of  64 | elapsed:   27.0s finished

In [26]:
joblib.load('../data/intermediate/step_06_mono/strat_saw.joblib')

         smi_enc  reac_enc  count strat      Sex         Age   Weight
0              1      1587      1   saw        F  Adolescent  Average
1              1      6165      1   saw        F  Adolescent  Average
2              1      7113      1   saw        F  Adolescent  Average
3              1      7617      1   saw        F  Adolescent  Average
4              1      7780      1   saw        F  Adolescent  Average
...          ...       ...    ...   ...      ...         ...      ...
2188328     2968     21537     40   saw  Unknown     Unknown  Unknown
2188329     2968     21553      2   saw  Unknown     Unknown  Unknown
2188330     2968     21590      5   saw  Unknown     Unknown  Unknown
2188331     2968     21633      1   saw  Unknown     Unknown  Unknown
2188332     2968     21641      4   saw  Unknown     Unknown  Unknown

[2188333 rows x 7 columns]

### Step 7

In [27]:
"""
In step 7 cardiotoxicity labels are assigned to reactions.

We're allowed to include the cardiotoxicity_terms.tsv as the number of terms is lower than 1000 and can be considered an example as per MedDRA license.
"""

"\nIn step 7 cardiotoxicity labels are assigned to reactions.\n\nWe're allowed to include the cardiotoxicity_terms.tsv as the number of terms is lower than 1000 and can be considered an example\nas per MedDRA license.\n"

In [28]:
# Map grouped PT terms to sets of idxs
os.makedirs(f'../data/intermediate/step_07_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_07_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_07_secondary', exist_ok=True)

groups = ['Cvas', 'Card', 'Cred']
pt_sets = read_df('../data/mappings/cardiotoxicity_terms.tsv')

sets_dc = {}

for group in groups:
    sets_dc[group] = pt_sets[pt_sets[group] == 1][terms_col].tolist()

joblib.dump(sets_dc, '../data/mappings/meddra_sets_pt_dict.joblib')

pt_2_idx = joblib.load('../data/mappings/pt_2_idx.joblib')

idx_dc = {}

for name, pts in sets_dc.items():
    idx_dc[name] = sorted([pt_2_idx.get(item) for item in pts])

joblib.dump(idx_dc, '../data/mappings/meddra_sets_idx_dict.joblib')

['../data/mappings/meddra_sets_idx_dict.joblib']

In [29]:
idx_dc = joblib.load('../data/mappings/meddra_sets_idx_dict.joblib')

def process_step_7(file, output_base_dir):
    strat_type = file.split('/')[-1].split('_')[-1].rstrip('.joblib')

    df = joblib.load(file)
    result_dfs = step_7(
        df=df,
        idx_dc=idx_dc,
        strat_type=strat_type
    )

    results = []

    for sub_df, pt_set, strat_type in result_dfs:

        pt_set_dir = f'{output_base_dir}/{pt_set}'
        os.makedirs(pt_set_dir, exist_ok=True)

        out_path = f'{pt_set_dir}/strat_{strat_type}.joblib'

        joblib.dump(sub_df, out_path)
        results.append((pt_set, strat_type))

    return results

tasks = []

for file in sorted(glob.glob(f'../data/intermediate/step_06_mono/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_07_mono'))

for file in sorted(glob.glob(f'../data/intermediate/step_06_primary/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_07_primary'))

for file in sorted(glob.glob(f'../data/intermediate/step_06_secondary/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_07_secondary'))

_ = Parallel(n_jobs=n_jobs, verbose=1, timeout=600)(
    delayed(process_step_7)(file, output_dir)
    for file, output_dir in tasks
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done  22 out of  24 | elapsed:   53.4s remaining:    4.9s
[Parallel(n_jobs=64)]: Done  24 out of  24 | elapsed:  1.2min finished

In [30]:
joblib.load('../data/intermediate/step_07_mono/Cred/strat_saw.joblib')

           Sex         Age   Weight  smi_enc  Cred  Cred_ct
0            F  Adolescent  Average        1     0        5
1            F  Adolescent  Average        5     0       94
2            F  Adolescent  Average        7     0     4504
3            F  Adolescent  Average        7     1        4
4            F  Adolescent  Average        8     0       69
...        ...         ...      ...      ...   ...      ...
44770  Unknown     Unknown  Unknown     2959     0      170
44771  Unknown     Unknown  Unknown     2959     1        1
44772  Unknown     Unknown  Unknown     2961     0      238
44773  Unknown     Unknown  Unknown     2968     0     3526
44774  Unknown     Unknown  Unknown     2968     1       79

[44775 rows x 6 columns]

### Step 8

In [ ]:
"""
In step 8 DPA contingency matrices are calculated for each data stratification level
"""

In [31]:
os.makedirs(f'../data/intermediate/step_08_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_08_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_08_secondary', exist_ok=True)

In [32]:
def process_step_8(file, output_base_dir):
    _, _, _, _, pt_set, strat_type = file.split('/')
    strat_type = strat_type.rstrip('.joblib').split('_')[-1]

    df = joblib.load(file)
    df = step_8(
        df=df,
        smiles_col='smi_enc',
        reaction_col=pt_set,
        count_col=f'{pt_set}_ct',
        pt_idx=1,
        strat_type=strat_type
    )

    os.makedirs(f'{output_base_dir}/{pt_set}', exist_ok=True)

    out_path = f'{output_base_dir}/{pt_set}/strat_{strat_type}.joblib'
    joblib.dump(df, out_path)

    return pt_set, strat_type

tasks = []

for file in sorted(glob.glob(f'../data/intermediate/step_07_mono/*/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_08_mono'))

for file in sorted(glob.glob(f'../data/intermediate/step_07_primary/*/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_08_primary'))

for file in sorted(glob.glob(f'../data/intermediate/step_07_secondary/*/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_08_secondary'))

_ = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
    delayed(process_step_8)(file, output_dir)
    for file, output_dir in tasks
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   9 out of  72 | elapsed:    6.1s remaining:   42.8s
[Parallel(n_jobs=64)]: Done  17 out of  72 | elapsed:    8.3s remaining:   26.8s
[Parallel(n_jobs=64)]: Done  25 out of  72 | elapsed:   10.0s remaining:   18.8s
[Parallel(n_jobs=64)]: Done  33 out of  72 | elapsed:   15.5s remaining:   18.4s
[Parallel(n_jobs=64)]: Done  41 out of  72 | elapsed:   19.6s remaining:   14.8s
[Parallel(n_jobs=64)]: Done  49 out of  72 | elapsed:   24.3s remaining:   11.4s
[Parallel(n_jobs=64)]: Done  57 out of  72 | elapsed:   31.8s remaining:    8.4s
[Parallel(n_jobs=64)]: Done  65 out of  72 | elapsed:   46.2s remaining:    5.0s
[Parallel(n_jobs=64)]: Done  72 out of  72 | elapsed:  1.4min finished

In [33]:
joblib.load('../data/intermediate/step_08_mono/Cred/strat_saw.joblib')

       smi_enc  Cred   a     b      c        d      Sex         Age   Weight
0            1     1   0     5    381    22646        F  Adolescent  Average
1            5     1   0    94    381    22557        F  Adolescent  Average
2            7     1   4  4504    377    18147        F  Adolescent  Average
3            8     1   3    69    378    22582        F  Adolescent  Average
4            9     1   7  5494    374    17157        F  Adolescent  Average
...        ...   ...  ..   ...    ...      ...      ...         ...      ...
31980     2948     1   0    44  67107  1557748  Unknown     Unknown  Unknown
31981     2958     1   0    10  67107  1557782  Unknown     Unknown  Unknown
31982     2959     1   1   170  67106  1557622  Unknown     Unknown  Unknown
31983     2961     1   0   238  67107  1557554  Unknown     Unknown  Unknown
31984     2968     1  79  3526  67028  1554266  Unknown     Unknown  Unknown

[31985 rows x 9 columns]

### Step 9

In [ ]:
"""
In step 9 the following operations are performed:
    - entries with insufficient amount of data to perform DPA are removed
    - the DPA metrics and confidence scores are calculated
    - the cardiotoxicity risk labels are assigned
    - risk labels are binarized
"""

In [34]:
# Division by 0 errors are caught automatically by Numpy and return np.nan
os.makedirs(f'../data/intermediate/step_09_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_09_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_09_secondary', exist_ok=True)

def process_step_9(file, output_base_dir):
    warnings.simplefilter(action='ignore', category=RuntimeWarning)
    _, _, _, _, pt_set, strat_type = file.split('/')
    strat_type = strat_type.rstrip('.joblib').split('_')[-1]

    df = joblib.load(file)
    df = step_9(
        df=df,
        min_records=3,   # minimum number of drug-adverse reaction to keep a record
        sign_level=0.01, # significance level for Confidence Interval calculation
        shrink=0.5,      # shrinkage factor for Information Component
        dist_power=0.5,  # distance-to-threshold power for sigmoid transformation of raw confidence scores
        saturation=2.5   # plateau value for sigmoid transformation of raw confidence scores
    )

    os.makedirs(f'{output_base_dir}/{pt_set}', exist_ok=True)

    out_path = f'{output_base_dir}/{pt_set}/strat_{strat_type}.joblib'
    joblib.dump(df, out_path)

    return pt_set, strat_type

tasks = []

for file in sorted(glob.glob(f'../data/intermediate/step_08_mono/*/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_09_mono'))

for file in sorted(glob.glob(f'../data/intermediate/step_08_primary/*/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_09_primary'))

for file in sorted(glob.glob(f'../data/intermediate/step_08_secondary/*/strat*.joblib')):
    tasks.append((file, '../data/intermediate/step_09_secondary'))

_ = Parallel(n_jobs=n_jobs, verbose=10, timeout=600)(
    delayed(process_step_9)(file, output_dir)
    for file, output_dir in tasks
)

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   9 out of  72 | elapsed:    1.5s remaining:   10.2s
[Parallel(n_jobs=64)]: Done  17 out of  72 | elapsed:    2.2s remaining:    7.1s
[Parallel(n_jobs=64)]: Done  25 out of  72 | elapsed:    2.6s remaining:    5.0s
[Parallel(n_jobs=64)]: Done  33 out of  72 | elapsed:    3.6s remaining:    4.2s
[Parallel(n_jobs=64)]: Done  41 out of  72 | elapsed:    4.8s remaining:    3.6s
[Parallel(n_jobs=64)]: Done  49 out of  72 | elapsed:    5.9s remaining:    2.8s
[Parallel(n_jobs=64)]: Done  57 out of  72 | elapsed:    7.9s remaining:    2.1s
[Parallel(n_jobs=64)]: Done  65 out of  72 | elapsed:   11.1s remaining:    1.2s
[Parallel(n_jobs=64)]: Done  72 out of  72 | elapsed:   21.0s finished

In [35]:
joblib.load('../data/intermediate/step_09_mono/Cred/strat_s.joblib')

,smi_enc,Cred,a,b,c,d,Sex,prr,prr_lower,prr_upper,...,prr_weight,prr_bin,ror_tox,ror_conf,ror_weight,ror_bin,ic_tox,ic_conf,ic_weight,ic_bin
0,1,1,69,9327,126359,5944756,F,0.35283,0.25903,0.48059,...,0.98497,0.0,Minimal,3.66469,0.98586,0.0,Minimal,1.36485,0.5503,0.0
1,5,1,4,322,126424,5953761,F,0.59011,0.16407,2.12243,...,0.16485,0.0,Low,0.32571,0.16456,0.0,Low,0.2212,0.14083,0.0
2,7,1,742,148805,125686,5805278,F,2.72309,2.47729,2.99327,...,0.90668,1.0,Minimal,596.330261,1.0,0.0,High,4.30945,0.9954,1.0
3,8,1,83,10855,126345,5943228,F,0.36454,0.27503,0.48318,...,0.98935,0.0,Minimal,3.86402,0.99,0.0,Minimal,1.47393,0.59715,0.0
4,9,1,1022,248537,125406,5705546,F,4.8393,4.46398,5.24618,...,0.90074,1.0,High,2.77017,0.93536,1.0,High,6.17272,0.99983,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3866,2948,1,0,44,70416,1688206,Unknown,<NA>,<NA>,<NA>,...,<NA>,NaN,Undefined,<NA>,<NA>,NaN,Undefined,<NA>,<NA>,NaN
3867,2958,1,0,10,70416,1688240,Unknown,<NA>,<NA>,<NA>,...,<NA>,NaN,Undefined,<NA>,<NA>,NaN,Undefined,<NA>,<NA>,NaN
3868,2959,1,1,171,70415,1688079,Unknown,0.14519,0.01113,1.8939,...,<NA>,NaN,Undefined,<NA>,<NA>,NaN,Undefined,<NA>,<NA>,NaN
3869,2961,1,1,242,70415,1688008,Unknown,0.10277,0.00786,1.3435,...,<NA>,NaN,Undefined,<NA>,<NA>,NaN,Undefined,<NA>,<NA>,NaN
3870,2968,1,100,4294,70316,1683956,Unknown,0.56778,0.44006,0.73256,...,0.85224,0.0,Minimal,2.26005,0.85513,0.0,Minimal,1.21135,0.48302,0.0

### Step 10

In [41]:
"""
In step 10 the results from DPA are aggregated and datatypes assigned. Generally, a lot of data manipulation.
"""

'\nIn step 10 the results from DPA are aggregated and datatypes assigned. Generally, a lot of data manipulation.\n'

In [36]:
os.makedirs(f'../data/intermediate/step_10_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_10_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_10_secondary', exist_ok=True)

In [37]:
drop_unknown = True
dpa_metrics = ['prr', 'ror', 'ic']

for dpa_metric in dpa_metrics:
    for directory in sorted(glob.glob(f'../data/intermediate/step_09_mono/*')):
        pt_type = directory.split('/')[-1]
        dfs = []
        for file in sorted(glob.glob(f'../data/intermediate/step_09_mono/{pt_type}/strat_*.joblib')):
            _, _, _, _, pt_set, strat_type = file.split('/')
            strat_type = strat_type.rstrip('.joblib').split('_')[-1]

            df = joblib.load(file)
            df = step_10(
                df=df,  # data
                strat_type=strat_type,  # type of stratification
                pt_type=pt_type,
                drop_unknown=drop_unknown,
                dpa_metric=dpa_metric
            )
            dfs.append(df)

        dfs = pd.concat(dfs, ignore_index = True)
        dfs = dfs.sort_values(by=['Sex', 'Age', 'Weight', 'smi_enc']).reset_index(drop=True)

        os.makedirs(f'../data/intermediate/step_10_mono/{pt_type}', exist_ok=True)
        joblib.dump(dfs, f'../data/intermediate/step_10_mono/{pt_type}/carbide_{dpa_metric}.joblib')

###

for dpa_metric in dpa_metrics:
    for directory in sorted(glob.glob(f'../data/intermediate/step_09_primary/*')):
        pt_type = directory.split('/')[-1]
        dfs = []
        for file in sorted(glob.glob(f'../data/intermediate/step_09_primary/{pt_type}/strat_*.joblib')):
            _, _, _, _, pt_set, strat_type = file.split('/')
            strat_type = strat_type.rstrip('.joblib').split('_')[-1]

            df = joblib.load(file)
            df = step_10(
                df=df,  # data
                strat_type=strat_type,  # type of stratification
                pt_type=pt_type,
                drop_unknown=drop_unknown,
                dpa_metric=dpa_metric
            )
            dfs.append(df)

        dfs = pd.concat(dfs, ignore_index = True)
        dfs = dfs.sort_values(by=['Sex', 'Age', 'Weight', 'smi_enc']).reset_index(drop=True)

        os.makedirs(f'../data/intermediate/step_10_primary/{pt_type}', exist_ok=True)
        joblib.dump(dfs, f'../data/intermediate/step_10_primary/{pt_type}/carbide_{dpa_metric}.joblib')

###

for dpa_metric in dpa_metrics:
    for directory in sorted(glob.glob(f'../data/intermediate/step_09_secondary/*')):
        pt_type = directory.split('/')[-1]
        dfs = []
        for file in sorted(glob.glob(f'../data/intermediate/step_09_secondary/{pt_type}/strat_*.joblib')):
            _, _, _, _, pt_set, strat_type = file.split('/')
            strat_type = strat_type.rstrip('.joblib').split('_')[-1]

            df = joblib.load(file)
            df = step_10(
                df=df,  # data
                strat_type=strat_type,  # type of stratification
                pt_type=pt_type,
                drop_unknown=drop_unknown,
                dpa_metric=dpa_metric
            )
            dfs.append(df)

        dfs = pd.concat(dfs, ignore_index = True)
        dfs = dfs.sort_values(by=['Sex', 'Age', 'Weight', 'smi_enc']).reset_index(drop=True)

        os.makedirs(f'../data/intermediate/step_10_secondary/{pt_type}', exist_ok=True)
        joblib.dump(dfs, f'../data/intermediate/step_10_secondary/{pt_type}/carbide_{dpa_metric}.joblib')

In [38]:
joblib.load('../data/intermediate/step_10_mono/Cred/carbide_prr.joblib')

,Strat,Sex,Age,Weight,smi_enc,prr,prr_lower,prr_upper,prr_tox,prr_bin,prr_conf,prr_weight,prr_smooth,a,b,c,d
0,saw,Male,Children,Low,302.0,3.50237,1.15811,10.59194,High,1.0,0.16768,0.12983,0.56492,5,46,232,8056
1,saw,Male,Children,Low,416.0,1.48875,0.68325,3.24387,Moderate,1.0,0.27301,0.15221,0.57610,11,253,226,7849
2,saw,Male,Children,Low,709.0,6.66907,1.72761,25.744579,High,1.0,0.09914,0.11681,0.55840,3,13,234,8089
3,saw,Male,Children,Low,861.0,0.99099,0.2754,3.566,Low,0.0,0.02885,0.10466,0.44767,4,138,233,7964
4,saw,Male,Children,Low,924.0,1.41983,0.53905,3.73976,Moderate,1.0,0.20243,0.13689,0.56844,7,168,230,7934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14992,n,Unknown,Unknown,Unknown,2943.0,0.84635,0.19467,3.67962,Low,0.0,0.11248,0.11925,0.44038,3,125,326554,11465582
14993,n,Unknown,Unknown,Unknown,2944.0,0.24902,0.10048,0.61714,Minimal,0.0,1.67697,0.67929,0.16036,8,1152,326549,11464555
14994,n,Unknown,Unknown,Unknown,2959.0,0.27047,0.12014,0.60891,Minimal,0.0,1.74714,0.70555,0.14722,10,1325,326547,11464382
14995,n,Unknown,Unknown,Unknown,2961.0,0.73795,0.38207,1.4253,Low,0.0,0.49065,0.20837,0.39582,15,719,326542,11464988
14996,n,Unknown,Unknown,Unknown,2968.0,2.73216,2.45727,3.0378,High,1.0,2.2667,0.85658,0.92829,581,33441,325976,11432266

### Step 11

In [39]:
"""
In step 11 the following operation are performed:
- decoding of SMILES indices
- encoding of demographic factors as numpy arrays (yes, again)
- concatenation of demographic arrays
- concatenation of demographic factors
- packing of values from DPA analysis
- column renaming, removal, and casting
"""

'\nIn step 11 the following operation are performed:\n- decoding of SMILES indices\n- encoding of demographic factors as numpy arrays (yes, again)\n- concatenation of demographic arrays\n- concatenation of demographic factors\n- packing of values from DPA analysis\n- column renaming, removal, and casting\n'

In [42]:
os.makedirs(f'../data/intermediate/step_11_mono', exist_ok=True)
os.makedirs(f'../data/intermediate/step_11_primary', exist_ok=True)
os.makedirs(f'../data/intermediate/step_11_secondary', exist_ok=True)
idx_2_smi = joblib.load('../data/mappings/idx_2_smi.joblib')

In [43]:
for file in tqdm(sorted(glob.glob(f'../data/intermediate/step_10_mono/*/carbide*.joblib')), total=9):
    _, _, _, _, pt_type, file_name = file.split('/')
    dpa_type = file.rstrip('.joblib').split('_')[-1]

    df = joblib.load(file)
    df = step_11(
        df=df,  # data
        smiles_col='smi_enc',  # column with smiles encoded as ints
        idx_2_smi=idx_2_smi,  # idx to smiles mapping
        dpa_metric=dpa_type
    )

    os.makedirs(f'../data/intermediate/step_11_mono/{pt_type}', exist_ok=True)
    out_path = f'../data/intermediate/step_11_mono/{pt_type}/carbide_{dpa_type}.joblib'
    joblib.dump(df, out_path)

###

for file in tqdm(sorted(glob.glob(f'../data/intermediate/step_10_primary/*/carbide*.joblib')), total=9):
    _, _, _, _, pt_type, file_name = file.split('/')
    dpa_type = file.rstrip('.joblib').split('_')[-1]

    df = joblib.load(file)
    df = step_11(
        df=df,  # data
        smiles_col='smi_enc',
        idx_2_smi=idx_2_smi,
        dpa_metric=dpa_type
    )

    os.makedirs(f'../data/intermediate/step_11_primary/{pt_type}', exist_ok=True)
    out_path = f'../data/intermediate/step_11_primary/{pt_type}/carbide_{dpa_type}.joblib'
    joblib.dump(df, out_path)

###

for file in tqdm(sorted(glob.glob(f'../data/intermediate/step_10_secondary/*/carbide*.joblib')), total=9):
    _, _, _, _, pt_type, file_name = file.split('/')
    dpa_type = file.rstrip('.joblib').split('_')[-1]

    df = joblib.load(file)
    df = step_11(
        df=df,  # data
        smiles_col='smi_enc',
        idx_2_smi=idx_2_smi,
        dpa_metric=dpa_type
    )

    os.makedirs(f'../data/intermediate/step_11_secondary/{pt_type}', exist_ok=True)
    out_path = f'../data/intermediate/step_11_secondary/{pt_type}/carbide_{dpa_type}.joblib'
    joblib.dump(df, out_path)

100%|██████████| 9/9 [00:07<00:00,  1.21it/s]
100%|██████████| 9/9 [00:12<00:00,  1.42s/it]
100%|██████████| 9/9 [00:18<00:00,  2.09s/it]

In [44]:
joblib.load('../data/intermediate/step_11_mono/Cred/carbide_prr.joblib')

,SMILES,Signature,Risk,Label,Label_confidence,Label_weight,Label_regression,DPA_confusion,DPA_values,DemoFP,Stratification
0,CC(C)(C)NCC(O)c1ccc(O)c(CO)c1,"(Male, Children, Low)",High,1,0.16768,0.12983,0.56492,"[5, 46, 232, 8056]","[3.50237, 1.15811, 10.59194]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw
1,CC(C)NCC(O)COc1cccc2ccccc12,"(Male, Children, Low)",Moderate,1,0.27301,0.15221,0.5761,"[11, 253, 226, 7849]","[1.48875, 0.68325, 3.24387]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw
2,CC1CC2C3CC=C4CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,"(Male, Children, Low)",High,1,0.09914,0.11681,0.5584,"[3, 13, 234, 8089]","[6.66907, 1.72761, 25.74458]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw
3,CCC1OC(=O)C(C)C(OC2CC(C)(OC)C(O)C(C)O2)C(C)C(O...,"(Male, Children, Low)",Low,0,0.02885,0.10466,0.44767,"[4, 138, 233, 7964]","[0.99099, 0.2754, 3.566]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw
4,CCCCCC(=O)OC1(C(C)=O)CCC2C3CC=C4CC(=O)CCC4(C)C...,"(Male, Children, Low)",Moderate,1,0.20243,0.13689,0.56844,"[7, 168, 230, 7934]","[1.41983, 0.53905, 3.73976]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw
...,...,...,...,...,...,...,...,...,...,...,...
14992,S=P(N1CC1)(N1CC1)N1CC1,"(Unknown, Unknown, Unknown)",Low,0,0.11248,0.11925,0.44038,"[3, 125, 326554, 11465582]","[0.84635, 0.19467, 3.67962]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n
14993,S=c1[nH]cnc2[nH]cnc12,"(Unknown, Unknown, Unknown)",Minimal,0,1.67697,0.67929,0.16036,"[8, 1152, 326549, 11464555]","[0.24902, 0.10048, 0.61714]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n
14994,c1ccc2c(CC3=NCCN3)cccc2c1,"(Unknown, Unknown, Unknown)",Minimal,0,1.74714,0.70555,0.14722,"[10, 1325, 326547, 11464382]","[0.27047, 0.12014, 0.60891]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n
14995,c1ccc2c(c1)CCCC2C1=NCCN1,"(Unknown, Unknown, Unknown)",Low,0,0.49065,0.20837,0.39582,"[15, 719, 326542, 11464988]","[0.73795, 0.38207, 1.4253]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n
14996,c1cnc2cc3c(cc2n1)C1CNCC3C1,"(Unknown, Unknown, Unknown)",High,1,2.2667,0.85658,0.92829,"[581, 33441, 325976, 11432266]","[2.73216, 2.45727, 3.0378]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n

### Step 12

In [ ]:
"""
In step 12, unique SMILES are clustered and assigned to folds.
Final datasets are prepared.
"""

In [46]:
import polars as pl
# Prepare the folds mapping

smis = set()
variants = ['Cvas', 'Card', 'Cred']

for file in tqdm(sorted(glob.glob('../data/intermediate/step_11*/*/carbide*.joblib'))):
    df = joblib.load(file).dropna(subset='SMILES')
    smis = smis.union(set(df['SMILES'].tolist()))

smis = sorted(smis)
df = pl.DataFrame({'SMILES': smis})

df_ecfp = dataframe_2_ecfp(df, radius=2, nbits=4096, n_jobs=16)

100%|██████████| 27/27 [00:08<00:00,  3.30it/s]
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   4 out of   4 | elapsed:    3.6s finished

In [47]:
df = butina_cluster(df_ecfp.to_pandas(), threshold=0.75)

gkf = GroupKFold(n_splits=5)

x_values = np.vstack(df['ECFP'].to_numpy())
y_values = np.zeros(shape=(len(df),))
groups = df.Cluster_ID.to_numpy()

df['Fold'] = -1
for fold, (_, test_idx) in enumerate(gkf.split(x_values, y_values, groups)):
    df.loc[test_idx, 'Fold'] = fold

df = df.drop(columns='ECFP')

df.to_csv('../data/mappings/data_splits.tsv', sep='\t', header=True, index=False)

In [48]:
os.makedirs('../data/carbide/mono', exist_ok=True)
os.makedirs('../data/carbide/primary', exist_ok=True)
os.makedirs('../data/carbide/secondary', exist_ok=True)
fold_df = read_df('../data/mappings/data_splits.tsv')

for file in tqdm(sorted(glob.glob('../data/intermediate/step_11*/*/carbide*.joblib')), total=27):
    _, _, _, step_type, pt_type, file_name = file.split('/')
    dpa_type = file.rstrip('.joblib').split('_')[-1]
    dataset_type = {'step_11_primary': 'primary', 'step_11_secondary': 'secondary', 'step_11_mono': 'mono'}.get(step_type)

    df = joblib.load(file)

    df = step_12(
        df=df,
        fold_df=fold_df,
        smiles_col='SMILES',
        dataset_type=dataset_type,
        dpa_type=dpa_type,
        pt_set=pt_type)

    os.makedirs(f'../data/carbide/{dataset_type}/{pt_type}', exist_ok=True)
    out_path = f'../data/carbide/{dataset_type}/{pt_type}/carbide_{dpa_type}.joblib'
    joblib.dump(df, out_path)

100%|██████████| 27/27 [00:16<00:00,  1.61it/s]

In [49]:
joblib.load('../data/carbide/mono/Cred/carbide_prr.joblib')

,SMILES,Signature,Risk,Label,Label_confidence,Label_weight,Label_regression,DPA_confusion,DPA_values,DemoFP,Stratification,Cluster_ID,Fold
0,CC(C)(C)NCC(O)c1ccc(O)c(CO)c1,"(Male, Children, Low)",High,1,0.16768,0.12983,0.56492,"[5, 46, 232, 8056]","[3.50237, 1.15811, 10.59194]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw,6,2
1,CC(C)NCC(O)COc1cccc2ccccc12,"(Male, Children, Low)",Moderate,1,0.27301,0.15221,0.5761,"[11, 253, 226, 7849]","[1.48875, 0.68325, 3.24387]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw,6,2
2,CC1CC2C3CC=C4CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,"(Male, Children, Low)",High,1,0.09914,0.11681,0.5584,"[3, 13, 234, 8089]","[6.66907, 1.72761, 25.74458]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw,14,4
3,CCC1OC(=O)C(C)C(OC2CC(C)(OC)C(O)C(C)O2)C(C)C(O...,"(Male, Children, Low)",Low,0,0.02885,0.10466,0.44767,"[4, 138, 233, 7964]","[0.99099, 0.2754, 3.566]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw,119,3
4,CCCCCC(=O)OC1(C(C)=O)CCC2C3CC=C4CC(=O)CCC4(C)C...,"(Male, Children, Low)",Moderate,1,0.20243,0.13689,0.56844,"[7, 168, 230, 7934]","[1.41983, 0.53905, 3.73976]","[1, 0, 1, 0, 0, 0, 1, 0, 0]",saw,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14992,S=P(N1CC1)(N1CC1)N1CC1,"(Unknown, Unknown, Unknown)",Low,0,0.11248,0.11925,0.44038,"[3, 125, 326554, 11465582]","[0.84635, 0.19467, 3.67962]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n,548,1
14993,S=c1[nH]cnc2[nH]cnc12,"(Unknown, Unknown, Unknown)",Minimal,0,1.67697,0.67929,0.16036,"[8, 1152, 326549, 11464555]","[0.24902, 0.10048, 0.61714]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n,149,2
14994,c1ccc2c(CC3=NCCN3)cccc2c1,"(Unknown, Unknown, Unknown)",Minimal,0,1.74714,0.70555,0.14722,"[10, 1325, 326547, 11464382]","[0.27047, 0.12014, 0.60891]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n,26,0
14995,c1ccc2c(c1)CCCC2C1=NCCN1,"(Unknown, Unknown, Unknown)",Low,0,0.49065,0.20837,0.39582,"[15, 719, 326542, 11464988]","[0.73795, 0.38207, 1.4253]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n,26,0
14996,c1cnc2cc3c(cc2n1)C1CNCC3C1,"(Unknown, Unknown, Unknown)",High,1,2.2667,0.85658,0.92829,"[581, 33441, 325976, 11432266]","[2.73216, 2.45727, 3.0378]","[0, 0, 0, 0, 0, 0, 0, 0, 0]",n,551,2

### Descriptors

In [50]:
import sys
sys.path.insert(0, '..')

from copy import deepcopy
from novami.data.descriptors import *
from src.data.io import *
"""
* Calculating CDDD embeddings requires setting up a separate environment. See src/cddd for setup scripts,
or visit https://github.com/jrwnter/cddd.
* Calculating ChemBERTa embeddings requires torch and transformers libraries
* Calculating descriptors requires novami:0.3.4 or later (probably). Install it via pip install git+https://github.com/M-Iwan/NovaMI.git or use other existing libraries
"""

cddd_path = '../../../cddd/files/CDDD_paths.json'

In [51]:
get_chemberta()

Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-100M-MLM and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [52]:
smi_df = read_df('../data/mappings/data_splits.tsv')[['SMILES']]

In [53]:
cddd = pl.from_pandas(dataframe_2_cddd(deepcopy(smi_df), cddd_paths=cddd_path, n_cpus=64))
klek = dataframe_2_klek(pl.from_pandas(smi_df),  n_jobs=16)
chemberta = dataframe_2_chemberta(pl.from_pandas(smi_df), n_jobs=16)
maccs = dataframe_2_maccs(pl.from_pandas(smi_df), n_jobs=16)
rdkit = dataframe_2_rdkit(pl.from_pandas(smi_df), n_jobs=16)
ecfp = dataframe_2_ecfp(pl.from_pandas(smi_df), radius=2, nbits=1024, n_jobs=16)

Consider installing the package zmq to utilize the InferenceServer class

2026-04-01 10:49:09.012333: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   4 out of   4 | elapsed:   11.0s finished
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   4 out of   4 | elapsed:   27.7s finished
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   4 out of   4 | elapsed:    2.2s finished
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   4 out of   4 | elapsed:    5.7s finished
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   4 out of   4 | elapsed:    0.3s finished

In [54]:
desc = maccs.join(klek, on='SMILES').join(rdkit, on='SMILES').join(ecfp, on='SMILES').join(cddd, on='SMILES').join(chemberta, on='SMILES')
joblib.dump(desc.to_pandas(), '../data/carbide/descriptors.joblib')

['../data/carbide/descriptors.joblib']

## Export as .tsv

In [21]:
from src.data.io import read_df, write_df
import polars as pl

for file in glob.glob('../data/carbide/*/*/*.joblib'):
    out_file = file.replace("joblib", "tsv")
    df = pl.from_pandas(read_df(file))
    df = df.with_columns([
        pl.col("Signature").list.join(';').alias("Signature"),
        pl.col("DPA_confusion").map_elements(
            lambda lst: ';'.join([str(item) for item in lst]),
            return_dtype=pl.String
        ),
        pl.col("DPA_values").map_elements(
            lambda lst: ';'.join([str(item) for item in lst]),
            return_dtype=pl.String
        ),
        pl.col("DemoFP").map_elements(
            lambda lst: ';'.join([str(item) for item in lst]),
            return_dtype=pl.String
        )
    ])
    write_df(df.to_pandas(), out_file)

In [27]:
dsc = pl.from_pandas(read_df("../data/carbide/descriptors.joblib"))
cols = dsc.columns
cols.remove("SMILES")
dsc = dsc.with_columns([
    pl.col(col_name).map_elements(
        lambda lst: ';'.join([str(item) for item in lst]),
        return_dtype=pl.String
    ).alias(col_name) for col_name in cols
])
write_df(dsc.to_pandas(), "../data/carbide/descriptors.tsv")